### ISSUE TITLE
dependency resolve-pkg-maps is missing in 2.27.5-2

### ISSUE THREAD

**Issue by ahippler** [un-es/eslint-plugin-i#8]
after the update from version 2.27.5-1 to 2.27.5-2 i get the error:

```
Oops! Something went wrong! :(

ESLint: 8.43.0

Error: Failed to load plugin 'import' declared in '.eslintrc.cjs': Cannot find module 'resolve-pkg-maps'
```

**Comment by Sparticuz** [comment]
I fixed mine by adding in resolve-pkg-maps to my dev dependencies, which seems to work.

**Comment by JounQin** [comment]
Interesting, this is because `get-tsconfig` requires `resolve-pkg-maps` at runtime, but we've downgraded it as vendor, I'll fix it ASAP.

**Comment by JounQin** [comment]
fixed
